### ISSUE TITLE
error on Gulp

### ISSUE THREAD

**Issue by huphtur** [dotmagic/markdown2pdf#1]
Tried running your setup, but getting errors
```
var conf = {
^^^

SyntaxError: Unexpected token var
etc etc
```
Are you using a newer Gulp version?

**Comment by dotmagic** [comment]
This line is just plain Javascript, nothing nodejs or gulp related. Its indeed weird. There's a missing semicolon in line 12 but it shouldn't cause this error since its optional in Javascript. 

Which platform are you using? Can you run other gulp scripts?

**Comment by huphtur** [comment]
Got it to work. Had to replace all the `,` to `;` at line 1-12, and install additional `through2` component.

**Comment by dotmagic** [comment]
Thanks. I see now I've just forgot to add throught2 to my package.json. I still dont understand why you had to change line 1-12, I'm using this syntax in various projects and plattforms.

**Comment by huphtur** [comment]
Yeah not sure either. Perhaps different Node versions? I'm on 4.4.4
